version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_up
    environment:
      POSTGRES_USER: scrapy_user
      POSTGRES_PASSWORD: scrapy_password
      POSTGRES_DB: scrapy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scrapy_user -d scrapy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app_up
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://scrapy_user:scrapy_password@postgres:5432/scrapy_db"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapy_app_up
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg2://scrapy_user:scrapy_password@postgres:5432/scrapy_db"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/testproject
    command: ["scrapy", "crawl", "trip"]

volumes:
  postgres_data: